### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by stilett0** [MooseValley/Physical-Activity-Coach#1]
Hey Moose! Unrelated to Physical-Activity-Coach, your website is down right now. Just an FYI!
http://moosesoftware.netau.net/
https://downforeveryoneorjustme.com/moosesoftware.netau.net/

**Comment by MooseValley** [comment]
Thanks Stilleto,
It's been an on-going issue with my web host provider for the last 2-3 weeks .... they say I am getting 10's of 1,000's of visitors a day to my web site.
The good old days of big visitor numbers to my web site are long gone.  Now it's just a nice sleepy back water.

StatCounter says I get 5-10 on average a day.  

And the Rebrandly redirector link says 11 people have clicked this link in the last month:
https://rebrand.ly/MoosesSoftware
I tend to believe StatCounter and Rebrandly and of course they aren't the ones trying to upsell me what I don't need / want.

Might have to move hosts again soon ....

Thanks for emailing.  Always great to hear from MAME / emulation guys and girls.  :)

Have a nice day.  :)  

 Mike "Moose" OMalley 
____________________________________________________
Moose's Software Valley - Established July, 1996.
 * Email: Moose_Software@yahoo.com.au 
* WEB Site:  https://rebrand.ly/MoosesSoftware* Discussion Forum on Reddit: https://www.reddit.com/r/MoosesSoftware/ 
* YouTube Channel: https://www.youtube.com/user/MoosesValley/playlists 
* GitHub source code: https://github.com/MooseValley?tab=repositories___________________________________________________ 


. 

    On Saturday, 15 February 2020, 6:42:37 am AEST, Stiletto <notifications@github.com> wrote:  
 
 
Hey Moose! Unrelated to Physical-Activity-Coach, your website is down right now. Just an FYI!
http://moosesoftware.netau.net/
https://downforeveryoneorjustme.com/moosesoftware.netau.net/

**Comment by MooseValley** [comment]
Hi Stilleto,

My web site is back up again - moved hosts to InfinityFree.  All going well so far.  😀

Web Site Link #1 (Rebrandly redirector - please bookmark this):
https://rebrand.ly/MoosesSoftware

Mike "Moose" OMalley
____________________________________________________
Moose's Software Valley - Established July, 1996.
* Email: Moose_Software@yahoo.com.au
* WEB Site:  https://rebrand.ly/MoosesSoftware
* Discussion Forum on Reddit: https://www.reddit.com/r/MoosesSoftware/
* YouTube Channel: https://www.youtube.com/user/MoosesValley/playlists
* GitHub source code: https://github.com/MooseValley?tab=repositories

**Comment by stilett0** [comment]
Thanks for the head's up! I will update the URL at MAMEWorld main page.

If things ever become dire, we may be able to provide "free" webhosting at MAMEWorld, though I wouldn't consider their hosting the most bulletproof either. The only general trend I know is that no ecommerce is done there.

If all your projects are free, with your growing involvement with Github, you may want to consider switching to https://pages.github.com/ :)
